# Generated by Django 2.0.2 on 2018-03-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Position',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='Speaker',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
				('Surname', models.CharField(max_length=100)),
				('email', models.CharField(max_length=100)),
				('Telephone', models.IntegerField()),
				('ProfileImage', models.ImageField(upload_to='')),
				('Bio', models.TextField()),
				('AnnouncementDateTime', models.DateTimeField(default=None)),
				('Announced', models.BooleanField(default=False)),
				('Presentation', models.FileField(upload_to='')),
				('PresentationReleaseDateTime', models.DateTimeField(default=None)),
				('PresentationRelease', models.BooleanField(default=False)),
				('Facebook', models.CharField(max_length=100)),
				('GitHub', models.CharField(max_length=100)),
				('GooglePlus', models.CharField(max_length=100)),
				('Instagram', models.CharField(max_length=100)),
				('LinkedIn', models.CharField(max_length=100)),
				('Pinterest', models.CharField(max_length=100)),
				('Twitter', models.CharField(max_length=100)),
				('YouTube', models.CharField(max_length=100)),
				('InternetLink', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='Sponsor',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('CompanyName', models.CharField(max_length=100)),
				('Name', models.CharField(max_length=100)),
				('Surname', models.CharField(max_length=100)),
				('email', models.CharField(max_length=100)),
				('Telephone', models.IntegerField()),
				('ProfileImage', models.ImageField(upload_to='')),
				('AnnouncementDateTime', models.DateTimeField(default=None)),
				('Announced', models.BooleanField(default=False)),
				('InternetLink', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='SponsorLevel',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='Team',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='TeamMember',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
				('Surname', models.CharField(max_length=100)),
				('email', models.CharField(max_length=100)),
				('Telephone', models.IntegerField()),
				('University', models.CharField(max_length=100)),
				('School', models.CharField(max_length=100)),
				('EducationalLevel', models.CharField(max_length=100)),
				('ProfileImage', models.ImageField(upload_to='')),
				('Bio', models.TextField()),
				('Facebook', models.CharField(max_length=100)),
				('GitHub', models.CharField(max_length=100)),
				('GooglePlus', models.CharField(max_length=100)),
				('Instagram', models.CharField(max_length=100)),
				('LinkedIn', models.CharField(max_length=100)),
				('Pinterest', models.CharField(max_length=100)),
				('Twitter', models.CharField(max_length=100)),
				('YouTube', models.CharField(max_length=100)),
				('Position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='TEDx2018.Position')),
			],
		),
		migrations.CreateModel(
			name='TeamMemberAssignment',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TEDx2018.Team')),
				('TeamMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEDx2018.TeamMember')),
			],
		),
		migrations.AddField(
			model_name='sponsor',
			name='SponsorLevel',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TEDx2018.SponsorLevel'),
		),
	]
