# Generated by Django 2.0.2 on 2018-03-09 23:48

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='ticket',
			name='Quantity',
		),
	]
