# Generated by Django 2.0.2 on 2018-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0002_remove_ticket_quantity'),
	]

	operations = [
		migrations.AlterField(
			model_name='event',
			name='EventImage',
			field=models.ImageField(blank=True, upload_to='TEDx2018/EventPictures/'),
		),
	]
