# Generated by Django 2.0.2 on 2018-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0002_auto_20180306_2308'),
	]

	operations = [
		migrations.AlterField(
			model_name='teammember',
			name='ProfileImage',
			field=models.ImageField(blank=True, default='defaultProfile.png', upload_to='images'),
		),
	]
