# Generated by Django 2.0.2 on 2018-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0003_auto_20180320_0139'),
	]

	operations = [
		migrations.RemoveField(
			model_name='partner',
			name='Announced',
		),
		migrations.RemoveField(
			model_name='speaker',
			name='Announced',
		),
		migrations.AddField(
			model_name='event',
			name='AnnouncementDateTime',
			field=models.DateTimeField(default=None, null=True),
		),
		migrations.AlterField(
			model_name='partner',
			name='AnnouncementDateTime',
			field=models.DateTimeField(default=None, null=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='AnnouncementDateTime',
			field=models.DateTimeField(default=None, null=True),
		),
	]
