# Generated by Django 2.0.2 on 2018-03-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0003_auto_20180306_2315'),
	]

	operations = [
		migrations.AlterField(
			model_name='teammember',
			name='ProfileImage',
			field=models.ImageField(blank=True, default='defaultProfile.png', upload_to='TEDx2018/TeamMemberProfilePictures/'),
		),
	]
