# Generated by Django 2.0.2 on 2018-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0005_auto_20180306_2334'),
	]

	operations = [
		migrations.AlterField(
			model_name='teammember',
			name='Bio',
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name='teammember',
			name='Facebook',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='GitHub',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='GooglePlus',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='Instagram',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='LinkedIn',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='Pinterest',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='Twitter',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='YouTube',
			field=models.CharField(blank=True, max_length=100),
		),
	]
