# Generated by Django 2.0.2 on 2018-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0005_auto_20180320_2111'),
	]

	operations = [
		migrations.AlterField(
			model_name='speaker',
			name='Surname',
			field=models.CharField(blank=True, max_length=100),
		),
	]
