# Generated by Django 2.0.2 on 2018-03-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0006_auto_20180306_2337'),
	]

	operations = [
		migrations.RemoveField(
			model_name='sponsor',
			name='ProfileImage',
		),
		migrations.AddField(
			model_name='sponsor',
			name='Logo',
			field=models.ImageField(blank=True, default='TEDx2018/Shared/defaultSponsorLogo.png', upload_to='TEDx2018/SponsorLogos/'),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Bio',
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Facebook',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='GitHub',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='GooglePlus',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Instagram',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='InternetLink',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='LinkedIn',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Pinterest',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Presentation',
			field=models.FileField(blank=True, upload_to='TEDx2018/SpeakerPresentations/'),
		),
		migrations.AlterField(
			model_name='speaker',
			name='ProfileImage',
			field=models.ImageField(blank=True, default='TEDx2018/Shared/defaultProfile.png', upload_to='TEDx2018/SpeakerProfilePictures/'),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Telephone',
			field=models.IntegerField(blank=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Twitter',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='YouTube',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='speaker',
			name='email',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='InternetLink',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='Name',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='Surname',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='Telephone',
			field=models.IntegerField(blank=True),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='email',
			field=models.CharField(blank=True, max_length=100),
		),
	]
