# Generated by Django 2.0.2 on 2018-03-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0006_auto_20180320_2204'),
	]

	operations = [
		migrations.AddField(
			model_name='teammember',
			name='InternetLink',
			field=models.CharField(blank=True, max_length=100),
		),
	]
