# Generated by Django 2.0.2 on 2018-03-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0007_teammember_internetlink'),
	]

	operations = [
		migrations.AlterField(
			model_name='event',
			name='AnnouncementDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
		migrations.AlterField(
			model_name='partner',
			name='AnnouncementDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='AnnouncementDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
	]
