# Generated by Django 2.0.2 on 2018-03-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0008_auto_20180321_0252'),
	]

	operations = [
		migrations.AddField(
			model_name='speaker',
			name='TalkSummary',
			field=models.TextField(blank=True),
		),
		migrations.AddField(
			model_name='speaker',
			name='TalkTitle',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AddField(
			model_name='speaker',
			name='TalkYouTubeLink',
			field=models.CharField(blank=True, max_length=100),
		),
	]
