# Generated by Django 2.0.2 on 2018-03-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0009_auto_20180306_2347'),
	]

	operations = [
		migrations.AlterField(
			model_name='sponsor',
			name='Telephone',
			field=models.IntegerField(blank=True, null=True),
		),
	]
