# Generated by Django 2.0.2 on 2018-03-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0010_auto_20180306_2349'),
	]

	operations = [
		migrations.AlterField(
			model_name='speaker',
			name='AnnouncementDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='PresentationReleaseDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
		migrations.AlterField(
			model_name='speaker',
			name='Telephone',
			field=models.IntegerField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='sponsor',
			name='AnnouncementDateTime',
			field=models.DateTimeField(blank=True, default=None, null=True),
		),
	]
