# Generated by Django 2.0.2 on 2018-03-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0010_partnerlevel_level'),
	]

	operations = [
		migrations.CreateModel(
			name='AboutUsCarouselPhotos',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Photo', models.ImageField(blank=True, default='TEDx2018/Shared/XBlackBig.svg', upload_to='TEDx2018/AboutUsCarouselPhotos/')),
				('Description', models.CharField(blank=True, max_length=100)),
				('Event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TEDx2018.Event')),
			],
		),
	]
