# Generated by Django 2.0.2 on 2018-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0011_aboutuscarouselphotos'),
	]

	operations = [
		migrations.RenameModel(
			old_name='AboutUsCarouselPhotos',
			new_name='AboutUsCarouselPhoto',
		),
	]
