# Generated by Django 2.0.2 on 2018-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0013_auto_20180322_1918'),
	]

	operations = [
		migrations.AddField(
			model_name='team',
			name='Photo',
			field=models.ImageField(blank=True, default='TEDx2018/Shared/XBlackBig.svg', upload_to='TEDx2018/TeamPhotos/'),
		),
	]
