# Generated by Django 2.0.2 on 2018-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0015_team_photodescription'),
	]

	operations = [
		migrations.RemoveField(
			model_name='event',
			name='EventDescription',
		),
		migrations.AddField(
			model_name='event',
			name='Description',
			field=models.TextField(blank=True),
		),
	]
