# Generated by Django 2.0.2 on 2018-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0016_auto_20180324_0138'),
	]

	operations = [
		migrations.RenameField(
			model_name='event',
			old_name='EventImage',
			new_name='CarouselImage',
		),
		migrations.AddField(
			model_name='event',
			name='Logo',
			field=models.ImageField(blank=True, default='TEDx2018/Shared/XBlackBig.svg', upload_to='TEDx2018/EventPictures/'),
		),
	]
