# Generated by Django 2.0.2 on 2018-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0017_auto_20180324_0139'),
	]

	operations = [
		migrations.RemoveField(
			model_name='event',
			name='SoldOut',
		),
		migrations.RemoveField(
			model_name='event',
			name='TicketsNumber',
		),
		migrations.AddField(
			model_name='event',
			name='TicketsAvailable',
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name='ticket',
			name='Available',
			field=models.BooleanField(default=True),
		),
		migrations.AlterField(
			model_name='event',
			name='Eventbrite',
			field=models.CharField(blank=True, default='#', max_length=100),
		),
	]
