# Generated by Django 2.0.2 on 2018-03-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0019_event_googlecalendarlink'),
	]

	operations = [
		migrations.CreateModel(
			name='Session',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('Name', models.CharField(max_length=100)),
				('Event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TEDx2018.Event')),
			],
		),
		migrations.AddField(
			model_name='speaker',
			name='TalkTime',
			field=models.TimeField(blank=True, default=None, null=True),
		),
		migrations.AddField(
			model_name='speaker',
			name='Session',
			field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TEDx2018.Session'),
		),
	]
