# Generated by Django 2.0.2 on 2018-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0020_auto_20180324_0520'),
	]

	operations = [
		migrations.AddField(
			model_name='speaker',
			name='HasSpoke',
			field=models.BooleanField(default=False),
		),
	]
