# Generated by Django 2.0.2 on 2018-03-24 03:35

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0021_speaker_hasspoke'),
	]

	operations = [
		migrations.RenameField(
			model_name='speaker',
			old_name='HasSpoke',
			new_name='HasSpoken',
		),
	]
