# Generated by Django 2.0.2 on 2018-03-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0022_auto_20180324_0535'),
	]

	operations = [
		migrations.AddField(
			model_name='event',
			name='IsOnGoing',
			field=models.BooleanField(default=False),
		),
	]
