# Generated by Django 2.0.2 on 2018-03-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0023_event_isongoing'),
	]

	operations = [
		migrations.AddField(
			model_name='event',
			name='ScheduleAnnounced',
			field=models.BooleanField(default=False),
		),
	]
