# Generated by Django 2.0.2 on 2018-03-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0025_auto_20180327_0525'),
	]

	operations = [
		migrations.AddField(
			model_name='event',
			name='Address2',
			field=models.CharField(blank=True, max_length=200),
		),
	]
