# Generated by Django 2.0.2 on 2018-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0027_event_hasannouncedspeakers'),
	]

	operations = [
		migrations.AlterField(
			model_name='teammember',
			name='EducationalLevel',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='School',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='Telephone',
			field=models.IntegerField(blank=True),
		),
		migrations.AlterField(
			model_name='teammember',
			name='University',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='teammember',
			name='email',
			field=models.CharField(blank=True, max_length=100),
		),
	]
