# Generated by Django 2.0.4 on 2018-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0029_auto_20180327_1546'),
	]

	operations = [
		migrations.AddField(
			model_name='teammember',
			name='ProfileImage2',
			field=models.ImageField(blank=True, default='TEDx2018/Shared/XWhite.svg', upload_to='TEDx2018/TeamMemberProfilePictures/'),
		),
	]
