# Generated by Django 2.0.4 on 2018-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0030_teammember_profileimage2'),
	]

	operations = [
		migrations.AlterField(
			model_name='teammember',
			name='ProfileImage2',
			field=models.ImageField(blank=True, upload_to='TEDx2018/TeamMemberProfilePictures/'),
		),
	]
