# Generated by Django 2.0.4 on 2018-04-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0032_auto_20180430_1807'),
	]

	operations = [
		migrations.AddField(
			model_name='workshop',
			name='HasSpoken',
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name='workshop',
			name='Session',
			field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TEDx2018.Session'),
		),
		migrations.AddField(
			model_name='workshop',
			name='TalkTime',
			field=models.TimeField(blank=True, default=None, null=True),
		),
	]
