# Generated by Django 2.0.4 on 2018-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0033_auto_20180501_0108'),
	]

	operations = [
		migrations.AddField(
			model_name='event',
			name='TicketsNumber',
			field=models.IntegerField(default=0),
		),
	]
