# Generated by Django 2.0.4 on 2018-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0035_auto_20180503_0305'),
	]

	operations = [
		migrations.AddField(
			model_name='session',
			name='Time',
			field=models.TimeField(blank=True, default=None, null=True),
		),
	]
