# Generated by Django 2.0.4 on 2018-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0036_session_time'),
	]

	operations = [
		migrations.AlterField(
			model_name='session',
			name='Time',
			field=models.TimeField(default='00:00'),
		),
	]
