# Generated by Django 2.0.4 on 2018-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('TEDx2018', '0037_auto_20180515_1737'),
	]

	operations = [
		migrations.AddField(
			model_name='workshop',
			name='isMain',
			field=models.BooleanField(default=True),
		),
	]
